### ISSUE TITLE
you are a fucking lunatic

### ISSUE THREAD

**Issue by King-BR** [Vladislav117/The-Biggest-Mod#1]
and i am one too
i will translate this shit
and how the fuck you made this?

**Comment by Vladislav117** [comment]
I wrote a python engine for mindustry mods. I did not expect a translation, since the names of items are generated randomly

**Comment by hippyrandall** [comment]
Jeebus I can't even load it! Do I need a supercomputer for this mod or what?

**Comment by King-BR** [comment]
im just waiting for him to post the engine on github
i will try to make a bigger mod
