### ISSUE TITLE
Please make the tech tree easier to use!

### ISSUE THREAD

**Issue by smb64** [Vladislav117/The-Biggest-Mod#3]
holy crap.... it takes me like 2 minutes of dragging my mouse across the screen repeatedly to get from one end of the tech tree to the other! please make it easier to use, like add a scroll bar or something, or a way to jump to different techs...

**Comment by Vladislav117** [comment]
I can’t do anything here. For now. It’s just that the mod is generated automatically, and I don’t know yet how to simplify the tree
